title: Work-in-Progress Seminars
logo: /assets/img/logo.jpg
description: Unless otherwise noted, all seminars will be held from <b>13:00–14:00</b> in <b>Room 113</b> in the Philosophy Department’s new building at <b><a href="https://maps.app.goo.gl/yNw7NHbTfU8RJFPW6">17 Wally's Walk</a></b>.<br><br>The seminars are followed by afternoon tea (that quaintest of Australian traditions—but yes, there’s coffee too) with the speaker, seminar attendees, and other members of the Philosophy Department. 
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
