title: Work-in-Progress Seminars
logo: /assets/img/logo.jpg
description: Schedule for the Philosophy Work-in-Progress Seminars at Macquarie University (Semester 2, 2024).
show_downloads: false
theme: jekyll-theme-minimal