title: Work-in-Progress Seminars
logo: /assets/img/logo.jpg
description: >
Schedule for the Philosophy Work-in-Progress Seminars at Macquarie University (Semester 2, 2024).

Unless otherwise noted, all seminars will be held from 13:00–14:30 in Room 224 (Moot Court) in the Philosophy Department’s new building at 17 Wally’s Walk.

The seminars are followed by afternoon tea (that quaintest of Australian traditions—but yes, there’s coffee too) with the speaker, seminar attendees, and other members of the Philosophy Department. 
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
